// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: grpc_gcp_sdk.proto

package grpcgcpsdk

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestCmd int32

const (
	RequestCmd_REQUESTCMDSTART RequestCmd = 0 //占位字段，有些语言对proto 数字0解析有差异，比如nodejs解析 0 为 undefined，因此有效数字从1开始
	RequestCmd_INITLINK        RequestCmd = 1 //初始化长连接通道，message_json字段格式{"deviceId": ""}
)

// Enum value maps for RequestCmd.
var (
	RequestCmd_name = map[int32]string{
		0: "REQUESTCMDSTART",
		1: "INITLINK",
	}
	RequestCmd_value = map[string]int32{
		"REQUESTCMDSTART": 0,
		"INITLINK":        1,
	}
)

func (x RequestCmd) Enum() *RequestCmd {
	p := new(RequestCmd)
	*p = x
	return p
}

func (x RequestCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gcp_sdk_proto_enumTypes[0].Descriptor()
}

func (RequestCmd) Type() protoreflect.EnumType {
	return &file_grpc_gcp_sdk_proto_enumTypes[0]
}

func (x RequestCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestCmd.Descriptor instead.
func (RequestCmd) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{0}
}

type ResponseCmd int32

const (
	ResponseCmd_RESPONSECMDSTART ResponseCmd = 0 //占位字段，有些语言对proto 数字0解析有差异，比如nodejs解析 0 为 undefined，因此有效数字从1开始
	ResponseCmd_SECURITYPOLICY   ResponseCmd = 1 //策略下发，接收到此cmd需要调用对应策略获取方法
)

// Enum value maps for ResponseCmd.
var (
	ResponseCmd_name = map[int32]string{
		0: "RESPONSECMDSTART",
		1: "SECURITYPOLICY",
	}
	ResponseCmd_value = map[string]int32{
		"RESPONSECMDSTART": 0,
		"SECURITYPOLICY":   1,
	}
)

func (x ResponseCmd) Enum() *ResponseCmd {
	p := new(ResponseCmd)
	*p = x
	return p
}

func (x ResponseCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gcp_sdk_proto_enumTypes[1].Descriptor()
}

func (ResponseCmd) Type() protoreflect.EnumType {
	return &file_grpc_gcp_sdk_proto_enumTypes[1]
}

func (x ResponseCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCmd.Descriptor instead.
func (ResponseCmd) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{1}
}

type ResponseCode int32

const (
	ResponseCode_RESPONSECODESTART ResponseCode = 0 //占位字段，有些语言对proto 数字0解析有差异，比如nodejs解析 0 为 undefined，因此有效数字从1开始
	ResponseCode_SUCCESS           ResponseCode = 1 //成功
	ResponseCode_SSLFAIL           ResponseCode = 2 //SSL证书加载失败
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSECODESTART",
		1: "SUCCESS",
		2: "SSLFAIL",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSECODESTART": 0,
		"SUCCESS":           1,
		"SSLFAIL":           2,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gcp_sdk_proto_enumTypes[2].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_grpc_gcp_sdk_proto_enumTypes[2]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{2}
}

type GegRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` //从uap导出的token信息
	DeviceId string `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
}

func (x *GegRequest) Reset() {
	*x = GegRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gcp_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GegRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GegRequest) ProtoMessage() {}

func (x *GegRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gcp_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GegRequest.ProtoReflect.Descriptor instead.
func (*GegRequest) Descriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *GegRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GegRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GegResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` //对应 ResponseCode 枚举的值
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GegResponse) Reset() {
	*x = GegResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gcp_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GegResponse) ProtoMessage() {}

func (x *GegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gcp_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GegResponse.ProtoReflect.Descriptor instead.
func (*GegResponse) Descriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *GegResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GegResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         int32            `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`                                   //对应 RequestCmd 枚举的值
	MessageJson string           `protobuf:"bytes,2,opt,name=message_json,json=messageJson,proto3" json:"message_json,omitempty"` //可以为json格式的字符串
	Data        *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ChaRequest) Reset() {
	*x = ChaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gcp_sdk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaRequest) ProtoMessage() {}

func (x *ChaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gcp_sdk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaRequest.ProtoReflect.Descriptor instead.
func (*ChaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *ChaRequest) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ChaRequest) GetMessageJson() string {
	if x != nil {
		return x.MessageJson
	}
	return ""
}

func (x *ChaRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         int32            `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`                                   //对应 ResponseCmd 枚举的值
	MessageJson string           `protobuf:"bytes,2,opt,name=message_json,json=messageJson,proto3" json:"message_json,omitempty"` //可以为json格式的字符串
	Data        *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ChaResponse) Reset() {
	*x = ChaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gcp_sdk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaResponse) ProtoMessage() {}

func (x *ChaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gcp_sdk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaResponse.ProtoReflect.Descriptor instead.
func (*ChaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_gcp_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *ChaResponse) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ChaResponse) GetMessageJson() string {
	if x != nil {
		return x.MessageJson
	}
	return ""
}

func (x *ChaResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_gcp_sdk_proto protoreflect.FileDescriptor

var file_grpc_gcp_sdk_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x63, 0x70, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x67, 0x63, 0x70, 0x73, 0x64, 0x6b,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e,
	0x0a, 0x0a, 0x47, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x3b,
	0x0a, 0x0b, 0x47, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6e, 0x0a, 0x0a, 0x43,
	0x68, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x2b,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x0b, 0x43,
	0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x2f, 0x0a, 0x0a,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x43, 0x4d, 0x44, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x49, 0x54, 0x4c, 0x49, 0x4e, 0x4b, 0x10, 0x01, 0x2a, 0x37, 0x0a,
	0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x43, 0x4d, 0x44, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x50, 0x4f,
	0x4c, 0x49, 0x43, 0x59, 0x10, 0x01, 0x2a, 0x3f, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x43, 0x4f, 0x44, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x53,
	0x4c, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x32, 0xa6, 0x01, 0x0a, 0x0a, 0x53, 0x44, 0x4b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x54, 0x68, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x63, 0x70, 0x73, 0x64, 0x6b, 0x2e, 0x47,
	0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x67, 0x63, 0x70, 0x73, 0x64, 0x6b, 0x2e, 0x47, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x15, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x67, 0x63, 0x70, 0x73, 0x64, 0x6b, 0x2e, 0x43, 0x68, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x63, 0x70, 0x73, 0x64, 0x6b,
	0x2e, 0x43, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x67, 0x63, 0x70, 0x73, 0x64, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_gcp_sdk_proto_rawDescOnce sync.Once
	file_grpc_gcp_sdk_proto_rawDescData = file_grpc_gcp_sdk_proto_rawDesc
)

func file_grpc_gcp_sdk_proto_rawDescGZIP() []byte {
	file_grpc_gcp_sdk_proto_rawDescOnce.Do(func() {
		file_grpc_gcp_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_gcp_sdk_proto_rawDescData)
	})
	return file_grpc_gcp_sdk_proto_rawDescData
}

var file_grpc_gcp_sdk_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_gcp_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_gcp_sdk_proto_goTypes = []interface{}{
	(RequestCmd)(0),         // 0: grpcgcpsdk.RequestCmd
	(ResponseCmd)(0),        // 1: grpcgcpsdk.ResponseCmd
	(ResponseCode)(0),       // 2: grpcgcpsdk.ResponseCode
	(*GegRequest)(nil),      // 3: grpcgcpsdk.GegRequest
	(*GegResponse)(nil),     // 4: grpcgcpsdk.GegResponse
	(*ChaRequest)(nil),      // 5: grpcgcpsdk.ChaRequest
	(*ChaResponse)(nil),     // 6: grpcgcpsdk.ChaResponse
	(*structpb.Struct)(nil), // 7: google.protobuf.Struct
}
var file_grpc_gcp_sdk_proto_depIdxs = []int32{
	7, // 0: grpcgcpsdk.ChaRequest.data:type_name -> google.protobuf.Struct
	7, // 1: grpcgcpsdk.ChaResponse.data:type_name -> google.protobuf.Struct
	3, // 2: grpcgcpsdk.SDKService.RegisterWithThePlatform:input_type -> grpcgcpsdk.GegRequest
	5, // 3: grpcgcpsdk.SDKService.LongConnectionChannel:input_type -> grpcgcpsdk.ChaRequest
	4, // 4: grpcgcpsdk.SDKService.RegisterWithThePlatform:output_type -> grpcgcpsdk.GegResponse
	6, // 5: grpcgcpsdk.SDKService.LongConnectionChannel:output_type -> grpcgcpsdk.ChaResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_gcp_sdk_proto_init() }
func file_grpc_gcp_sdk_proto_init() {
	if File_grpc_gcp_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_gcp_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GegRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_gcp_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GegResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_gcp_sdk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_gcp_sdk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_gcp_sdk_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_gcp_sdk_proto_goTypes,
		DependencyIndexes: file_grpc_gcp_sdk_proto_depIdxs,
		EnumInfos:         file_grpc_gcp_sdk_proto_enumTypes,
		MessageInfos:      file_grpc_gcp_sdk_proto_msgTypes,
	}.Build()
	File_grpc_gcp_sdk_proto = out.File
	file_grpc_gcp_sdk_proto_rawDesc = nil
	file_grpc_gcp_sdk_proto_goTypes = nil
	file_grpc_gcp_sdk_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SDKServiceClient is the client API for SDKService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SDKServiceClient interface {
	RegisterWithThePlatform(ctx context.Context, in *GegRequest, opts ...grpc.CallOption) (*GegResponse, error)
	LongConnectionChannel(ctx context.Context, opts ...grpc.CallOption) (SDKService_LongConnectionChannelClient, error)
}

type sDKServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSDKServiceClient(cc grpc.ClientConnInterface) SDKServiceClient {
	return &sDKServiceClient{cc}
}

func (c *sDKServiceClient) RegisterWithThePlatform(ctx context.Context, in *GegRequest, opts ...grpc.CallOption) (*GegResponse, error) {
	out := new(GegResponse)
	err := c.cc.Invoke(ctx, "/grpcgcpsdk.SDKService/RegisterWithThePlatform", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDKServiceClient) LongConnectionChannel(ctx context.Context, opts ...grpc.CallOption) (SDKService_LongConnectionChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SDKService_serviceDesc.Streams[0], "/grpcgcpsdk.SDKService/LongConnectionChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &sDKServiceLongConnectionChannelClient{stream}
	return x, nil
}

type SDKService_LongConnectionChannelClient interface {
	Send(*ChaRequest) error
	Recv() (*ChaResponse, error)
	grpc.ClientStream
}

type sDKServiceLongConnectionChannelClient struct {
	grpc.ClientStream
}

func (x *sDKServiceLongConnectionChannelClient) Send(m *ChaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sDKServiceLongConnectionChannelClient) Recv() (*ChaResponse, error) {
	m := new(ChaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SDKServiceServer is the server API for SDKService service.
type SDKServiceServer interface {
	RegisterWithThePlatform(context.Context, *GegRequest) (*GegResponse, error)
	LongConnectionChannel(SDKService_LongConnectionChannelServer) error
}

// UnimplementedSDKServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSDKServiceServer struct {
}

func (*UnimplementedSDKServiceServer) RegisterWithThePlatform(context.Context, *GegRequest) (*GegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWithThePlatform not implemented")
}
func (*UnimplementedSDKServiceServer) LongConnectionChannel(SDKService_LongConnectionChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method LongConnectionChannel not implemented")
}

func RegisterSDKServiceServer(s *grpc.Server, srv SDKServiceServer) {
	s.RegisterService(&_SDKService_serviceDesc, srv)
}

func _SDKService_RegisterWithThePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServiceServer).RegisterWithThePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcgcpsdk.SDKService/RegisterWithThePlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServiceServer).RegisterWithThePlatform(ctx, req.(*GegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDKService_LongConnectionChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SDKServiceServer).LongConnectionChannel(&sDKServiceLongConnectionChannelServer{stream})
}

type SDKService_LongConnectionChannelServer interface {
	Send(*ChaResponse) error
	Recv() (*ChaRequest, error)
	grpc.ServerStream
}

type sDKServiceLongConnectionChannelServer struct {
	grpc.ServerStream
}

func (x *sDKServiceLongConnectionChannelServer) Send(m *ChaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sDKServiceLongConnectionChannelServer) Recv() (*ChaRequest, error) {
	m := new(ChaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SDKService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcgcpsdk.SDKService",
	HandlerType: (*SDKServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWithThePlatform",
			Handler:    _SDKService_RegisterWithThePlatform_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LongConnectionChannel",
			Handler:       _SDKService_LongConnectionChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_gcp_sdk.proto",
}
